openapi: 3.0.1
info:
  title: Maximo APIKEY TEMP
  description: ''
  version: '1.0'
servers:
  - url: https://gateway.apiportaltst.ns.nl/MXAPIAPIKEY
paths:
  /create:
    post:
      summary: RestAPI key
      description: RestAPI key
      operationId: restapi-key
      parameters:
        - name: MAXAUTH
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]